// AUTO-GENERATED by a backtracking fill generator. Each entry is a self-contained
// 5x5 mini: a solution grid (# = black square) plus across/down clues with the
// answer, starting cell (row,col) and length. Crossings are consistent by
// construction because every clue is read from the single solution grid.

export const PUZZLES = [
  {
    grid: ["ROD##", "OPEN#", "TACIT", "#LACE", "##YEN"],
    across: [
      { num: 1, clue: "Fishing pole", answer: "ROD", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Not shut", answer: "OPEN", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Unspoken", answer: "TACIT", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Shoe string", answer: "LACE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Japanese cash", answer: "YEN", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Decay", answer: "ROT", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Iridescent gem", answer: "OPAL", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Rot", answer: "DECAY", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Pleasant", answer: "NICE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Perfect score", answer: "TEN", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["ELM##", "BEAT#", "BASIS", "#PORE", "##NET"],
    across: [
      { num: 1, clue: "Shade tree", answer: "ELM", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Drum rhythm", answer: "BEAT", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Foundation", answer: "BASIS", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Skin opening", answer: "PORE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Goal mesh", answer: "NET", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Tide's retreat", answer: "EBB", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Big jump", answer: "LEAP", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Bricklayer", answer: "MASON", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Wheel rubber", answer: "TIRE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Group", answer: "SET", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["ELM##", "ROOF#", "ARRAY", "#DARE", "##LET"],
    across: [
      { num: 1, clue: "Shade tree", answer: "ELM", row: 0, col: 0, len: 3 },
      { num: 4, clue: "House top", answer: "ROOF", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Ordered display", answer: "ARRAY", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Challenge", answer: "DARE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Allow", answer: "LET", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Time period", answer: "ERA", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Noble title", answer: "LORD", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Story lesson", answer: "MORAL", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Bus cost", answer: "FARE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "So far", answer: "YET", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["ROB##", "OMEN#", "DIGIT", "#TACO", "##NET"],
    across: [
      { num: 1, clue: "Steal from", answer: "ROB", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Sign of things to come", answer: "OMEN", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Single number", answer: "DIGIT", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Folded tortilla", answer: "TACO", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Goal mesh", answer: "NET", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Fishing pole", answer: "ROD", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Leave out", answer: "OMIT", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Started", answer: "BEGAN", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Pleasant", answer: "NICE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Toddler", answer: "TOT", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["ROT##", "IRON#", "BATON", "#LAVA", "##LAB"],
    across: [
      { num: 1, clue: "Decay", answer: "ROT", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Wrinkle remover", answer: "IRON", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Relay stick", answer: "BATON", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Volcano flow", answer: "LAVA", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Science room", answer: "LAB", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Chest bone", answer: "RIB", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Spoken", answer: "ORAL", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Sum", answer: "TOTAL", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Bright star", answer: "NOVA", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Catch", answer: "NAB", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["RIM##", "ATOM#", "METER", "#MIRE", "##FED"],
    across: [
      { num: 1, clue: "Wheel edge", answer: "RIM", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Tiny particle", answer: "ATOM", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Poetry rhythm", answer: "METER", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Bog", answer: "MIRE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Gave food to", answer: "FED", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Battering tool", answer: "RAM", row: 0, col: 0, len: 3 },
      { num: 2, clue: "List entry", answer: "ITEM", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Recurring theme", answer: "MOTIF", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Just a", answer: "MERE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Stop-sign color", answer: "RED", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["RIM##", "ATOM#", "PETAL", "#MODE", "##RED"],
    across: [
      { num: 1, clue: "Wheel edge", answer: "RIM", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Tiny particle", answer: "ATOM", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Flower part", answer: "PETAL", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Manner", answer: "MODE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Stop-sign color", answer: "RED", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Rhyme genre", answer: "RAP", row: 0, col: 0, len: 3 },
      { num: 2, clue: "List entry", answer: "ITEM", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Engine", answer: "MOTOR", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Created", answer: "MADE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Guided", answer: "LED", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["LOT##", "IRON#", "PATIO", "#LAND", "##LED"],
    across: [
      { num: 1, clue: "Parking ___", answer: "LOT", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Wrinkle remover", answer: "IRON", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Backyard space", answer: "PATIO", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Terra firma", answer: "LAND", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Guided", answer: "LED", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Mouth edge", answer: "LIP", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Spoken", answer: "ORAL", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Sum", answer: "TOTAL", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Baseball team size", answer: "NINE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Strange", answer: "ODD", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["ROT##", "UPON#", "MANIA", "#LEND", "##RED"],
    across: [
      { num: 1, clue: "Decay", answer: "ROT", row: 0, col: 0, len: 3 },
      { num: 4, clue: "On top of", answer: "UPON", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Craze", answer: "MANIA", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Loan out", answer: "LEND", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Stop-sign color", answer: "RED", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Pirate's drink", answer: "RUM", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Iridescent gem", answer: "OPAL", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Printer ink", answer: "TONER", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Baseball team size", answer: "NINE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Sum up", answer: "ADD", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["RUB##", "OPAL#", "TOTAL", "#NONE", "##NET"],
    across: [
      { num: 1, clue: "Massage", answer: "RUB", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Iridescent gem", answer: "OPAL", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Sum", answer: "TOTAL", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Not any", answer: "NONE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Goal mesh", answer: "NET", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Decay", answer: "ROT", row: 0, col: 0, len: 3 },
      { num: 2, clue: "On top of", answer: "UPON", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Relay stick", answer: "BATON", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Bowling alley", answer: "LANE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Allow", answer: "LET", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["RAM##", "ITEM#", "MOTOR", "#MARE", "##LED"],
    across: [
      { num: 1, clue: "Battering tool", answer: "RAM", row: 0, col: 0, len: 3 },
      { num: 4, clue: "List entry", answer: "ITEM", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Engine", answer: "MOTOR", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Female horse", answer: "MARE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Guided", answer: "LED", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Wheel edge", answer: "RIM", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Tiny particle", answer: "ATOM", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Iron or gold", answer: "METAL", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Additional", answer: "MORE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Stop-sign color", answer: "RED", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["ROB##", "OVEN#", "TALON", "#LONE", "##WET"],
    across: [
      { num: 1, clue: "Steal from", answer: "ROB", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Baking box", answer: "OVEN", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Eagle's claw", answer: "TALON", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Solitary", answer: "LONE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Soaked", answer: "WET", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Decay", answer: "ROT", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Egg shape", answer: "OVAL", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Underneath", answer: "BELOW", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Not any", answer: "NONE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Goal mesh", answer: "NET", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["ROD##", "OMIT#", "BEGAN", "#NICE", "##TOW"],
    across: [
      { num: 1, clue: "Fishing pole", answer: "ROD", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Leave out", answer: "OMIT", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Started", answer: "BEGAN", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Pleasant", answer: "NICE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Pull along", answer: "TOW", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Steal from", answer: "ROB", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Sign of things to come", answer: "OMEN", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Single number", answer: "DIGIT", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Folded tortilla", answer: "TACO", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Brand-___", answer: "NEW", row: 2, col: 4, len: 3 },
    ],
  },
  {
    grid: ["RED##", "OPEN#", "TIMID", "#CONE", "##NEW"],
    across: [
      { num: 1, clue: "Stop-sign color", answer: "RED", row: 0, col: 0, len: 3 },
      { num: 4, clue: "Not shut", answer: "OPEN", row: 1, col: 0, len: 4 },
      { num: 6, clue: "Shy", answer: "TIMID", row: 2, col: 0, len: 5 },
      { num: 8, clue: "Ice cream holder", answer: "CONE", row: 3, col: 1, len: 4 },
      { num: 9, clue: "Brand-___", answer: "NEW", row: 4, col: 2, len: 3 },
    ],
    down: [
      { num: 1, clue: "Decay", answer: "ROT", row: 0, col: 0, len: 3 },
      { num: 2, clue: "Grand tale", answer: "EPIC", row: 0, col: 1, len: 4 },
      { num: 3, clue: "Evil spirit", answer: "DEMON", row: 0, col: 2, len: 5 },
      { num: 5, clue: "Baseball team size", answer: "NINE", row: 1, col: 3, len: 4 },
      { num: 7, clue: "Morning moisture", answer: "DEW", row: 2, col: 4, len: 3 },
    ],
  },
];

// Daily rotation: a deterministic index from the local calendar date so the
// puzzle changes at local midnight and is identical for everyone that day.
const EPOCH = Date.UTC(2024, 0, 1); // 2024-01-01
const DAY_MS = 86400000;

export function dayIndexFor(date = new Date()) {
  // Use the local Y/M/D (not UTC) so the change happens at the players midnight.
  const local = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  return Math.floor((local - EPOCH) / DAY_MS);
}

export function getDailyPuzzle(date = new Date()) {
  const idx = ((dayIndexFor(date) % PUZZLES.length) + PUZZLES.length) % PUZZLES.length;
  return { puzzle: PUZZLES[idx], index: idx };
}
