#!/usr/bin/env node
/*
 * pipeline/credits.mjs — regenerate the asset-sources block in CREDITS.md from
 * `art-recipes/sources.jsonl`.
 *
 * §22 R17 wants every source that reaches the game credited. CC0 imposes no
 * legal attribution duty, which is exactly why this has to be automated: a
 * courtesy nobody is obliged to perform is a courtesy that silently rots. The
 * ledger is the single place a source is declared; this renders it.
 *
 * Everything outside the managed markers is hand-written and preserved — the
 * AI tool/model credits §22 R17 also asks for live there.
 *
 *   node pipeline/credits.mjs           rewrite the managed block
 *   node pipeline/credits.mjs --check   fail if the block is stale (for CI)
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const LEDGER = join(ROOT, "art-recipes", "sources.jsonl");
const CREDITS = join(ROOT, "CREDITS.md");

const BEGIN = "<!-- BEGIN:asset-sources (generated by pipeline/credits.mjs — do not edit) -->";
const END = "<!-- END:asset-sources -->";

const SCAFFOLD = `# Credits

Every external source that reaches the game, and every AI tool used to make
something that does. Required by \`GALLOWS_HYMN.md\` §22 R17.

## AI tools and models

Hand-maintained. Per-generation detail lives in \`art-recipes/prompts.jsonl\` and
\`art-recipes/audio-prompts.jsonl\`; this section names the tools.

<!-- Add entries here as tools are actually used. -->

## Asset sources

${BEGIN}
${END}
`;

const CLASS_LABEL = {
  "character-base": "Character base",
  "character-variant": "Character variants",
  animation: "Animation",
  kit: "Modular kit",
  props: "Props",
  texture: "Textures",
  hdri: "Lighting",
};

async function readLedger() {
  const text = await readFile(LEDGER, "utf8");
  return text
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("//"))
    .map((l) => JSON.parse(l));
}

function render(rows) {
  const byClass = new Map();
  for (const r of rows) {
    if (!byClass.has(r.class)) byClass.set(r.class, []);
    byClass.get(r.class).push(r);
  }

  const authors = [...new Set(rows.map((r) => r.author))].sort();
  const out = [];

  out.push(
    `All ${rows.length} sources below are **CC0 1.0** — public domain dedication, no`,
    `attribution required. They are credited anyway, because the people who released`,
    `them for free deserve the name-check and because provenance is cheaper to keep`,
    `than to reconstruct.`,
    "",
    `Thanks to: ${authors.map((a) => `**${a}**`).join(" · ")}.`,
    "",
  );

  for (const [cls, list] of byClass) {
    out.push(`### ${CLASS_LABEL[cls] ?? cls}`, "");
    out.push("| Source | Author | Licence | Covers |");
    out.push("| --- | --- | --- | --- |");
    for (const r of list) {
      if (!r.page) throw new Error(`${r.id} has no page URL — cannot credit it`);
      out.push(`| [${r.id}](${r.page}) | ${r.author} | ${r.licence} | ${r.covers} |`);
    }
    out.push("");
  }

  out.push(
    "Fetched and hashed by `pipeline/vendor.mjs`; the exact bytes in use are pinned",
    "in `art-recipes/sources.lock.json`.",
  );

  return out.join("\n");
}

async function main() {
  const check = process.argv.includes("--check");
  const rows = await readLedger();
  const block = `${BEGIN}\n\n${render(rows)}\n\n${END}`;

  let existing;
  try {
    existing = await readFile(CREDITS, "utf8");
  } catch {
    existing = SCAFFOLD;
  }

  if (!existing.includes(BEGIN) || !existing.includes(END)) {
    existing = existing.trimEnd() + `\n\n## Asset sources\n\n${BEGIN}\n${END}\n`;
  }

  const next = existing.replace(
    new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}`),
    () => block,
  );

  if (check) {
    if (next !== existing) {
      console.error("CREDITS.md is stale — run `npm run art:credits`");
      process.exit(1);
    }
    console.log("CREDITS.md is up to date.");
    return;
  }

  await writeFile(CREDITS, next, "utf8");
  console.log(`CREDITS.md updated — ${rows.length} CC0 sources credited.`);
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

main().catch((e) => {
  console.error(`credits.mjs failed — ${e.message}`);
  process.exit(1);
});
