// Word data for the "Word Imposter" party game. 10 categories, 100 words each.

export const CATEGORIES = [
  {
    id: "movies",
    name: "Movies",
    icon: "fa-film",
    words: [
      "The Matrix", "Titanic", "Jurassic Park", "Star Wars", "The Godfather",
      "Forrest Gump", "Avatar", "Inception", "The Lion King", "Frozen",
      "Jaws", "Rocky", "Gladiator", "Braveheart", "The Avengers",
      "Iron Man", "Spider-Man", "Batman", "Superman", "Black Panther",
      "Pulp Fiction", "Fight Club", "The Shining", "Psycho", "Alien",
      "Predator", "Terminator", "Die Hard", "Speed", "Top Gun",
      "Grease", "Footloose", "Dirty Dancing", "Pretty Woman", "Casablanca",
      "Gone Girl", "Se7en", "The Departed", "Goodfellas", "Scarface",
      "Joker", "Dune", "Interstellar", "Gravity", "The Martian",
      "Toy Story", "Up", "Finding Nemo", "Shrek", "Cars",
      "Coco", "Moana", "Encanto", "Aladdin", "Cinderella",
      "Snow White", "Bambi", "Dumbo", "Tarzan", "Mulan",
      "The Hangover", "Superbad", "Bridesmaids", "Anchorman", "Zoolander",
      "Mean Girls", "Clueless", "Juno", "La La Land", "Whiplash",
      "Parasite", "Oldboy", "Memento", "Shutter Island", "The Prestige",
      "Gone With the Wind", "Ben-Hur", "The Sound of Music", "Mary Poppins", "Singin in the Rain",
      "Jumanji", "Ghostbusters", "Home Alone", "Elf", "The Grinch",
      "Harry Potter", "Twilight", "The Hunger Games", "Maze Runner", "Divergent",
      "The Lord of the Rings", "The Hobbit", "King Kong", "Godzilla", "Pacific Rim",
      "Saving Private Ryan", "Schindler's List", "Apocalypse Now", "Full Metal Jacket", "1917"
    ]
  },
  {
    id: "animals",
    name: "Animals",
    icon: "fa-paw",
    words: [
      "Lion", "Tiger", "Elephant", "Giraffe", "Zebra",
      "Hippopotamus", "Rhinoceros", "Cheetah", "Leopard", "Panther",
      "Bear", "Panda", "Koala", "Kangaroo", "Wolf",
      "Fox", "Deer", "Moose", "Bison", "Buffalo",
      "Horse", "Donkey", "Camel", "Llama", "Alpaca",
      "Cow", "Pig", "Sheep", "Goat", "Chicken",
      "Duck", "Goose", "Turkey", "Rooster", "Peacock",
      "Eagle", "Hawk", "Owl", "Falcon", "Vulture",
      "Parrot", "Penguin", "Flamingo", "Ostrich", "Swan",
      "Dog", "Cat", "Rabbit", "Hamster", "Guinea Pig",
      "Mouse", "Rat", "Squirrel", "Hedgehog", "Bat",
      "Dolphin", "Whale", "Shark", "Octopus", "Squid",
      "Jellyfish", "Crab", "Lobster", "Shrimp", "Starfish",
      "Seahorse", "Turtle", "Tortoise", "Crocodile", "Alligator",
      "Snake", "Lizard", "Chameleon", "Iguana", "Gecko",
      "Frog", "Toad", "Salamander", "Newt", "Axolotl",
      "Bee", "Wasp", "Ant", "Butterfly", "Moth",
      "Spider", "Scorpion", "Beetle", "Ladybug", "Dragonfly",
      "Monkey", "Gorilla", "Chimpanzee", "Orangutan", "Sloth",
      "Otter", "Beaver", "Raccoon", "Skunk", "Platypus"
    ]
  },
  {
    id: "foods-and-drinks",
    name: "Foods & Drinks",
    icon: "fa-utensils",
    words: [
      "Pizza", "Hamburger", "Hot Dog", "Sandwich", "Taco",
      "Burrito", "Sushi", "Ramen", "Spaghetti", "Lasagna",
      "Macaroni", "Pancakes", "Waffles", "French Toast", "Bacon",
      "Eggs", "Omelette", "Cereal", "Toast", "Bagel",
      "Croissant", "Donut", "Muffin", "Cupcake", "Brownie",
      "Cookie", "Cake", "Pie", "Cheesecake", "Ice Cream",
      "Chocolate", "Candy", "Lollipop", "Gummy Bears", "Popcorn",
      "Pretzel", "Chips", "Fries", "Nachos", "Onion Rings",
      "Steak", "Chicken Wings", "Meatballs", "Sausage", "Ribs",
      "Salmon", "Tuna", "Shrimp", "Fish and Chips", "Calamari",
      "Salad", "Soup", "Stew", "Chili", "Curry",
      "Rice", "Noodles", "Dumplings", "Spring Rolls", "Fried Rice",
      "Apple", "Banana", "Orange", "Strawberry", "Watermelon",
      "Grapes", "Pineapple", "Mango", "Peach", "Cherry",
      "Lemon", "Avocado", "Tomato", "Carrot", "Broccoli",
      "Potato", "Corn", "Cheese", "Yogurt", "Butter",
      "Honey", "Peanut Butter", "Jam", "Ketchup", "Mustard",
      "Coffee", "Tea", "Hot Chocolate", "Milkshake", "Smoothie",
      "Lemonade", "Orange Juice", "Soda", "Cola", "Water",
      "Beer", "Wine", "Champagne", "Whiskey", "Cocktail"
    ]
  },
  {
    id: "sports-and-activities",
    name: "Sports & Activities",
    icon: "fa-futbol",
    words: [
      "Soccer", "Basketball", "Baseball", "Football", "Hockey",
      "Tennis", "Golf", "Cricket", "Rugby", "Volleyball",
      "Badminton", "Table Tennis", "Squash", "Bowling", "Billiards",
      "Boxing", "Wrestling", "Karate", "Judo", "Taekwondo",
      "Fencing", "Archery", "Shooting", "Darts", "Curling",
      "Swimming", "Diving", "Surfing", "Sailing", "Rowing",
      "Kayaking", "Canoeing", "Water Polo", "Snorkeling", "Scuba Diving",
      "Skiing", "Snowboarding", "Ice Skating", "Sledding", "Bobsled",
      "Running", "Sprinting", "Marathon", "Hurdles", "Long Jump",
      "High Jump", "Pole Vault", "Javelin", "Shot Put", "Discus",
      "Cycling", "Mountain Biking", "Skateboarding", "Rollerblading", "Parkour",
      "Climbing", "Hiking", "Camping", "Fishing", "Hunting",
      "Horse Riding", "Polo", "Netball", "Lacrosse", "Handball",
      "Gymnastics", "Cheerleading", "Dancing", "Ballet", "Yoga",
      "Pilates", "Weightlifting", "CrossFit", "Aerobics", "Zumba",
      "Bungee Jumping", "Skydiving", "Paragliding", "Hang Gliding", "Zip Lining",
      "Chess", "Poker", "Dominoes", "Checkers", "Backgammon",
      "Paintball", "Laser Tag", "Frisbee", "Dodgeball", "Kickball",
      "Motor Racing", "Go-Karting", "Drifting", "Rally", "Motocross",
      "Triathlon", "Decathlon", "Cross Country", "Race Walking", "Tug of War"
    ]
  },
  {
    id: "countries-and-cities",
    name: "Countries & Cities",
    icon: "fa-earth-americas",
    words: [
      "France", "Germany", "Italy", "Spain", "Portugal",
      "England", "Ireland", "Scotland", "Greece", "Netherlands",
      "Belgium", "Switzerland", "Austria", "Sweden", "Norway",
      "Denmark", "Finland", "Poland", "Russia", "Ukraine",
      "Turkey", "Egypt", "Morocco", "Kenya", "Nigeria",
      "South Africa", "Brazil", "Argentina", "Chile", "Peru",
      "Mexico", "Canada", "United States", "Cuba", "Jamaica",
      "China", "Japan", "South Korea", "India", "Thailand",
      "Vietnam", "Indonesia", "Philippines", "Malaysia", "Singapore",
      "Australia", "New Zealand", "Iceland", "Croatia", "Hungary",
      "Paris", "London", "Rome", "Madrid", "Barcelona",
      "Berlin", "Amsterdam", "Vienna", "Prague", "Athens",
      "Lisbon", "Dublin", "Edinburgh", "Venice", "Florence",
      "Moscow", "Istanbul", "Cairo", "Dubai", "Mumbai",
      "Tokyo", "Kyoto", "Beijing", "Shanghai", "Hong Kong",
      "Seoul", "Bangkok", "Singapore City", "Sydney", "Melbourne",
      "New York", "Los Angeles", "Chicago", "Miami", "Las Vegas",
      "San Francisco", "Toronto", "Vancouver", "Montreal", "Mexico City",
      "Rio de Janeiro", "Buenos Aires", "Lima", "Bogota", "Havana",
      "Nairobi", "Cape Town", "Marrakech", "Reykjavik", "Helsinki"
    ]
  },
  {
    id: "famous-people",
    name: "Famous People",
    icon: "fa-user-tie",
    words: [
      "Albert Einstein", "Isaac Newton", "Charles Darwin", "Nikola Tesla", "Galileo",
      "Leonardo da Vinci", "Michelangelo", "Vincent van Gogh", "Pablo Picasso", "Claude Monet",
      "William Shakespeare", "Mark Twain", "Charles Dickens", "Jane Austen", "Ernest Hemingway",
      "Abraham Lincoln", "George Washington", "Winston Churchill", "Napoleon", "Julius Caesar",
      "Cleopatra", "Alexander the Great", "Genghis Khan", "Mahatma Gandhi", "Nelson Mandela",
      "Martin Luther King", "John F. Kennedy", "Barack Obama", "Queen Elizabeth", "Princess Diana",
      "Mother Teresa", "Marie Curie", "Stephen Hawking", "Steve Jobs", "Bill Gates",
      "Elon Musk", "Mark Zuckerberg", "Walt Disney", "Henry Ford", "Thomas Edison",
      "Wolfgang Mozart", "Ludwig van Beethoven", "Johann Bach", "Elvis Presley", "Michael Jackson",
      "The Beatles", "Madonna", "Beyonce", "Taylor Swift", "Lady Gaga",
      "Freddie Mercury", "David Bowie", "Bob Marley", "Frank Sinatra", "Whitney Houston",
      "Marilyn Monroe", "Audrey Hepburn", "Charlie Chaplin", "Alfred Hitchcock", "Steven Spielberg",
      "Tom Hanks", "Leonardo DiCaprio", "Brad Pitt", "Johnny Depp", "Robert De Niro",
      "Meryl Streep", "Julia Roberts", "Angelina Jolie", "Jennifer Lawrence", "Will Smith",
      "Denzel Washington", "Morgan Freeman", "Arnold Schwarzenegger", "Sylvester Stallone", "Jackie Chan",
      "Bruce Lee", "Muhammad Ali", "Michael Jordan", "LeBron James", "Pele",
      "Diego Maradona", "Lionel Messi", "Cristiano Ronaldo", "Usain Bolt", "Serena Williams",
      "Roger Federer", "Tiger Woods", "Tom Brady", "Babe Ruth", "Wayne Gretzky",
      "Oprah Winfrey", "Ellen DeGeneres", "Kim Kardashian", "Kanye West", "Rihanna",
      "Drake", "Eminem", "Snoop Dogg", "Justin Bieber", "Ariana Grande"
    ]
  },
  {
    id: "household-objects",
    name: "Household Objects",
    icon: "fa-couch",
    words: [
      "Sofa", "Chair", "Table", "Bed", "Desk",
      "Bookshelf", "Wardrobe", "Dresser", "Nightstand", "Cabinet",
      "Lamp", "Chandelier", "Candle", "Flashlight", "Mirror",
      "Clock", "Calendar", "Picture Frame", "Vase", "Rug",
      "Curtain", "Blanket", "Pillow", "Cushion", "Mattress",
      "Television", "Remote Control", "Speaker", "Radio", "Headphones",
      "Refrigerator", "Oven", "Microwave", "Toaster", "Kettle",
      "Blender", "Mixer", "Coffee Maker", "Dishwasher", "Stove",
      "Plate", "Bowl", "Cup", "Mug", "Glass",
      "Fork", "Knife", "Spoon", "Chopsticks", "Spatula",
      "Pot", "Pan", "Frying Pan", "Cutting Board", "Colander",
      "Washing Machine", "Dryer", "Iron", "Vacuum Cleaner", "Broom",
      "Mop", "Bucket", "Dustpan", "Sponge", "Trash Can",
      "Towel", "Soap", "Toothbrush", "Toothpaste", "Shampoo",
      "Toilet", "Sink", "Bathtub", "Shower", "Faucet",
      "Door", "Window", "Key", "Doorknob", "Doorbell",
      "Stairs", "Carpet", "Fireplace", "Radiator", "Thermostat",
      "Scissors", "Stapler", "Tape", "Glue", "Pen",
      "Pencil", "Eraser", "Notebook", "Umbrella", "Backpack",
      "Wallet", "Keys", "Phone Charger", "Battery", "Light Bulb"
    ]
  },
  {
    id: "jobs-and-professions",
    name: "Jobs & Professions",
    icon: "fa-briefcase",
    words: [
      "Doctor", "Nurse", "Dentist", "Surgeon", "Pharmacist",
      "Teacher", "Professor", "Principal", "Tutor", "Librarian",
      "Lawyer", "Judge", "Police Officer", "Detective", "Firefighter",
      "Soldier", "Pilot", "Flight Attendant", "Sailor", "Astronaut",
      "Engineer", "Architect", "Scientist", "Programmer", "Electrician",
      "Plumber", "Carpenter", "Mechanic", "Welder", "Painter",
      "Chef", "Baker", "Butcher", "Waiter", "Bartender",
      "Barista", "Farmer", "Fisherman", "Gardener", "Florist",
      "Accountant", "Banker", "Cashier", "Salesperson", "Manager",
      "Secretary", "Receptionist", "Consultant", "Analyst", "Economist",
      "Journalist", "Reporter", "Editor", "Author", "Translator",
      "Actor", "Singer", "Dancer", "Musician", "Comedian",
      "Artist", "Photographer", "Designer", "Sculptor", "Animator",
      "Veterinarian", "Zookeeper", "Biologist", "Chemist", "Physicist",
      "Psychologist", "Therapist", "Counselor", "Social Worker", "Paramedic",
      "Tailor", "Hairdresser", "Barber", "Makeup Artist", "Manicurist",
      "Driver", "Taxi Driver", "Bus Driver", "Truck Driver", "Delivery Driver",
      "Construction Worker", "Miner", "Lumberjack", "Surveyor", "Janitor",
      "Politician", "Mayor", "President", "Diplomat", "Ambassador",
      "Athlete", "Coach", "Referee", "Lifeguard", "Personal Trainer"
    ]
  },
  {
    id: "video-games",
    name: "Video Games",
    icon: "fa-gamepad",
    words: [
      "Super Mario", "The Legend of Zelda", "Pokemon", "Sonic", "Donkey Kong",
      "Metroid", "Kirby", "Star Fox", "Pac-Man", "Tetris",
      "Space Invaders", "Street Fighter", "Mortal Kombat", "Tekken", "Smash Bros",
      "Minecraft", "Roblox", "Fortnite", "Among Us", "Fall Guys",
      "Call of Duty", "Battlefield", "Halo", "Doom", "Wolfenstein",
      "Counter-Strike", "Valorant", "Overwatch", "Apex Legends", "Rainbow Six",
      "Grand Theft Auto", "Red Dead Redemption", "Mafia", "Watch Dogs", "Saints Row",
      "The Witcher", "Skyrim", "Fallout", "Elden Ring", "Dark Souls",
      "Bloodborne", "Sekiro", "Horizon", "God of War", "The Last of Us",
      "Uncharted", "Tomb Raider", "Resident Evil", "Silent Hill", "Dead Space",
      "Assassin's Creed", "Far Cry", "Prince of Persia", "Hitman", "Splinter Cell",
      "Final Fantasy", "Kingdom Hearts", "Dragon Quest", "Chrono Trigger", "Persona",
      "League of Legends", "Dota", "World of Warcraft", "Diablo", "Starcraft",
      "Hearthstone", "Clash of Clans", "Candy Crush", "Angry Birds", "Temple Run",
      "FIFA", "Madden", "NBA 2K", "Rocket League", "Gran Turismo",
      "Mario Kart", "Need for Speed", "Forza", "Burnout", "Crash Team Racing",
      "The Sims", "Animal Crossing", "Stardew Valley", "Terraria", "Cities Skylines",
      "Civilization", "Age of Empires", "Command and Conquer", "SimCity", "Tropico",
      "Cyberpunk 2077", "Mass Effect", "Borderlands", "Bioshock", "Portal",
      "Half-Life", "Crash Bandicoot", "Spyro", "Rayman", "Cuphead"
    ]
  },
  {
    id: "music-and-instruments",
    name: "Music & Instruments",
    icon: "fa-music",
    words: [
      "Guitar", "Bass Guitar", "Electric Guitar", "Acoustic Guitar", "Ukulele",
      "Violin", "Viola", "Cello", "Double Bass", "Harp",
      "Piano", "Keyboard", "Organ", "Accordion", "Harpsichord",
      "Drums", "Snare Drum", "Bass Drum", "Bongos", "Tambourine",
      "Cymbals", "Triangle", "Xylophone", "Marimba", "Glockenspiel",
      "Flute", "Clarinet", "Oboe", "Bassoon", "Piccolo",
      "Saxophone", "Trumpet", "Trombone", "Tuba", "French Horn",
      "Harmonica", "Bagpipes", "Recorder", "Pan Flute", "Didgeridoo",
      "Banjo", "Mandolin", "Sitar", "Synthesizer", "Turntable",
      "Rock", "Pop", "Jazz", "Blues", "Country",
      "Hip Hop", "Rap", "Reggae", "Soul", "Funk",
      "Disco", "Techno", "House", "Electronic", "Dubstep",
      "Classical", "Opera", "Folk", "Punk", "Metal",
      "Heavy Metal", "Grunge", "Indie", "R&B", "Gospel",
      "The Beatles", "The Rolling Stones", "Queen", "Led Zeppelin", "Pink Floyd",
      "Nirvana", "Metallica", "AC/DC", "U2", "Coldplay",
      "Michael Jackson", "Elvis Presley", "Bob Dylan", "Bruce Springsteen", "David Bowie",
      "Beyonce", "Taylor Swift", "Adele", "Ed Sheeran", "Bruno Mars",
      "Eminem", "Drake", "Kanye West", "Jay-Z", "Snoop Dogg",
      "ABBA", "Bee Gees", "Fleetwood Mac", "The Eagles", "Bon Jovi"
    ]
  }
];
