/*
 * sim/math.ts — deterministic maths for the simulation.
 *
 * `Math.sin`/`cos`/`tan`/`pow`/`exp` are IMPLEMENTATION-DEFINED in JavaScript:
 * V8 and SpiderMonkey disagree in the last bits. That's fine for pixels and
 * fatal for a replay that must reproduce bit-identically in another browser
 * (GALLOWS_HYMN.md §13, rule 5).
 *
 * So the sim uses its own sin/cos: a lookup table generated by a Taylor series
 * that only ever uses + - * /, all of which ARE exactly specified by IEEE-754.
 * `Math.PI` is safe too (the spec pins it to the nearest double), and
 * `Math.sqrt` is exact. Everything else is off-limits below this file.
 */

export const TAU = Math.PI * 2;
export const HALF_PI = Math.PI / 2;

const TABLE_BITS = 12;
const TABLE_SIZE = 1 << TABLE_BITS; // 4096 entries over a full turn
const TABLE_SCALE = TABLE_SIZE / TAU;

/** sin via Taylor series — deterministic across engines (only + - * /). */
function taylorSin(x: number): number {
  // Converges comfortably inside double precision for |x| <= PI.
  const x2 = x * x;
  let term = x;
  let sum = x;
  for (let n = 1; n <= 10; n++) {
    term = (-term * x2) / ((2 * n) * (2 * n + 1));
    sum += term;
  }
  return sum;
}

// One extra entry so the interpolation below never needs a wrap-around branch.
const SIN_TABLE = new Float64Array(TABLE_SIZE + 1);
for (let i = 0; i <= TABLE_SIZE; i++) {
  // Reduce to [-PI, PI] before the series, where it's most accurate.
  let a = (i / TABLE_SIZE) * TAU;
  if (a > Math.PI) a -= TAU;
  SIN_TABLE[i] = taylorSin(a);
}

/** Deterministic sine. Max error ~3e-7 — far below anything gameplay can see. */
export function dsin(a: number): number {
  let t = a * TABLE_SCALE;
  t = t - Math.floor(t / TABLE_SIZE) * TABLE_SIZE; // wrap into [0, TABLE_SIZE)
  const i = t | 0;
  const f = t - i;
  const s0 = SIN_TABLE[i];
  return s0 + (SIN_TABLE[i + 1] - s0) * f;
}

/** Deterministic cosine. */
export function dcos(a: number): number {
  return dsin(a + HALF_PI);
}

export function clamp(v: number, lo: number, hi: number): number {
  return v < lo ? lo : v > hi ? hi : v;
}

export function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

/** Move `v` toward `target` by at most `maxDelta`. */
export function approach(v: number, target: number, maxDelta: number): number {
  const d = target - v;
  if (d > maxDelta) return v + maxDelta;
  if (d < -maxDelta) return v - maxDelta;
  return target;
}

export function len2(x: number, z: number): number {
  return Math.sqrt(x * x + z * z);
}

/** Shortest signed angular difference from `a` to `b`, in (-PI, PI]. */
export function angleDelta(a: number, b: number): number {
  let d = (b - a) % TAU;
  if (d > Math.PI) d -= TAU;
  if (d < -Math.PI) d += TAU;
  return d;
}

/**
 * Quantize a float before it enters the simulation. Unquantized mouse deltas
 * are the classic desync source, and quantizing also shrinks the replay log
 * (§13, rule 7).
 */
export function quantize(v: number, steps: number): number {
  return Math.round(v * steps) / steps;
}
